// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0bmNxGeUnGu5Xd6AHhhnwBEc5G2r-zHI',
    appId: '1:248615485321:web:27c89949dfa1071e096b58',
    messagingSenderId: '248615485321',
    projectId: 'reddit-clone-f3886',
    authDomain: 'reddit-clone-f3886.firebaseapp.com',
    storageBucket: 'reddit-clone-f3886.appspot.com',
    measurementId: 'G-8W648B0GY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO3rqTfS1h0S0kRmOWHjGcwnGK8hop_io',
    appId: '1:248615485321:android:679e122d510da853096b58',
    messagingSenderId: '248615485321',
    projectId: 'reddit-clone-f3886',
    storageBucket: 'reddit-clone-f3886.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIGCTBsmBHmueadi8EGIUWpzFZM4yOk3w',
    appId: '1:248615485321:ios:77897332d825e235096b58',
    messagingSenderId: '248615485321',
    projectId: 'reddit-clone-f3886',
    storageBucket: 'reddit-clone-f3886.appspot.com',
    androidClientId: '248615485321-7gthr3ipkc55ioto5kj0vebetlaov9su.apps.googleusercontent.com',
    iosClientId: '248615485321-6u1u40kisknn4mqiljiv5jt36q83fnps.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIGCTBsmBHmueadi8EGIUWpzFZM4yOk3w',
    appId: '1:248615485321:ios:77897332d825e235096b58',
    messagingSenderId: '248615485321',
    projectId: 'reddit-clone-f3886',
    storageBucket: 'reddit-clone-f3886.appspot.com',
    androidClientId: '248615485321-7gthr3ipkc55ioto5kj0vebetlaov9su.apps.googleusercontent.com',
    iosClientId: '248615485321-6u1u40kisknn4mqiljiv5jt36q83fnps.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );
}
